### ISSUE TITLE
Training patch size problem

### ISSUE THREAD

**Issue by XiaoBuL** [Boyan-Lenin-Xu/GCResNet#4]
Hello, I'm confused about the patch size 240 you set in options.xml, while patch size 256 in the paper? If I want to train with 256x256 patch size, is it any impact?

**Comment by Boyan-Lenin-Xu** [comment]
Thanks for your attention. There is no restriction on the patch size, you can change the patch size to fit your GPU memory.

**Comment by XiaoBuL** [comment]
But once I change the patch size to 256x256, there would be size error in graph down_sample layers  (this layer's stride is set to 10) and graph up_sample layers. Do I need to change the stride to fit the patch size?

**Comment by Boyan-Lenin-Xu** [comment]
The size of feature map may be different after upsample, because the number can not be divided by stride. (e.g., for 256x256, after two down samples it would be 64x64, which is not a multiple of 10) In this code, the patch size is set to 240 to fit most of GPUs. You can change the stride or the output padding of upsample.

**Comment by XiaoBuL** [comment]
I change the stride or the output padding of upsample  layer,  it can fit the training patch size 256 rightly. But when testing, it brings same size problem. Is it necessary to use dimension decrease before GCN?

**Comment by Boyan-Lenin-Xu** [comment]
It it not theoretically necessary, but if you do not use down sample before GCN, it will lead to large memory cost of GPU memory.

**Comment by XiaoBuL** [comment]
ok, thanks for your response!
